### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by dexterslabor** [iammortimer/TN-WAVES-Gateway#1]
Hi and thank you for your work. 
I wanted to try out the gateway, but receive the following error:

```sh
$ python start.py
Traceback (most recent call last):
  File "start.py", line 11, in <module>
    config = json.load(json_file)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

I would appreciate any help in debugging this.

**Comment by iammortimer** [comment]
Hi Dexter,

looks like your config.json is incomplete / corrupted, did you replace all the values?

**Comment by dexterslabor** [comment]
Overlooked one variable. After that my problem was that I have used a wrong port number and it took a long time to get the timeout error.

**Comment by iammortimer** [comment]
Glad you got it sorted, let me know if you run into anything else.
